drinkManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drinks.urls')),
    path('statistics/', include('stats.urls'))
]

drinks/urls.py
from django.urls import path

from .views import views, drinks, user, prices

urlpatterns = [
    # base views
    path('', views.dashboard, name="dashboard"),
    path('history', views.history, name="history"),
    path('history/undo/<int:sale_id>', views.undo_sale, name="undo_sale"),

    # ordering logic
    path('order/<int:user_id>', views.order_user, name="order_user"),
    path('order/<int:user_id>/<int:product_id>', views.order_drink, name="order_full"),

    # user administration
    path('user/dashboard', user.user_dashboard, name="user_dashboard"),
    path('user/add', user.user_add, name="user_add"),
    path('user/<int:user_id>/edit', user.user_edit, name="user_edit"),
    path('user/pay', user.pay, name="user_pay"),
    path('user/transfer', user.transfer, name="user_transfer"),

    # drink administration
    path('drink/dashboard', drinks.drinks, name="drinks"),
    path('drink/add', drinks.drink_add, name='drink_add'),
    path('drink/<int:drink_id>/edit', drinks.drink_edit, name='drink_edit'),
    path('drink/<int:drink_id>/toggle', drinks.drink_toggle, name="drink_toggle"),
    path('drink/<int:drink_id>/changePrice', drinks.drink_change_price, name="drink_change_price"),
    path('drink/<int:drink_id>/restock', drinks.drink_restock, name="drink_restock"),
    path('drink/<int:drink_id>/count', drinks.drink_count, name="drink_count"),
    path('drink/recalculate', drinks.drink_recalculate_stock, name="drink_recalc_stock"),

    # price administration
    path('prices/dashboard', prices.prices_dashboard, name="prices_dashboard"),
    path('prices/add', prices.add, name="prices_add"),
    path('prices/<int:price_id>/edit', prices.edit, name="prices_edit"),
]

stats/urls.py
from django.urls import path

from .views import views, data

app_name = "statistics"

urlpatterns = [
    path('drinks', views.stock, name="stock"),
    path('drinksofuser', views.drinks_of_user, name="drinks_of_user"),
    path('usersofdrink', views.users_of_drink, name="users_of_drink"),

    # data
    path('data/stock', data.stock, name="api_stock"),
    path('data/loss', data.loss, name="api_loss"),
]

drinks/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from django.forms import ModelForm, Form, IntegerField, RadioSelect, HiddenInput

from .models import Product, Profile, Transaction, Price


class ChangePriceForm(ModelForm):
    class Meta:
        model = Product
        fields = ['current_price']

    def __init__(self, *args, **kwargs):
        super(ChangePriceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('current_price')
        )


class DrinkForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'current_price', 'image', 'active', 'dashboard_order', 'chart_color']

        help_texts = {
            'image': "Square images fit best. If your don't upload one, a white square is used instead."
        }

    def __init__(self, *args, **kwargs):
        super(DrinkForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False
        self.helper = FormHelper()
        self.helper.form_tag = False


class RestockForm(Form):
    bottles = IntegerField(min_value=0, required=True, initial=0)

    def __init__(self, *args, **kwargs):
        super(RestockForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('bottles')
        )


class UserEditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['username', 'active', 'sorting_order', 'room_number']
        widgets = {
            'sorting_order': RadioSelect()
        }

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('username'),
            InlineRadios('sorting_order'),
            Div('active'),
            Div('room_number')
        )


class DebtForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['target', 'amount']

    def __init__(self, hide_source=False, *args, **kwargs):
        super(DebtForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('target'),
            Div('amount'),
        )

        if hide_source:
            self.fields['target'].widget = HiddenInput()


class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['target', 'source', 'amount']

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('source'),
            Div('target'),
            Div('amount'),
        )


class PriceForm(ModelForm):
    class Meta:
        model = Price
        fields = ['name', 'description', 'amount']

    def __init__(self, *args, **kwargs):
        super(PriceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div('name'),
            Div('description'),
            Div('amount'),
        )

drinks/views/drinks.py
from django.shortcuts import redirect, render

from drinks.forms import DrinkForm, ChangePriceForm, RestockForm
from drinks.models import Product, InventoryCheck


def drink_add(request):
    if request.method == 'POST':
        f = DrinkForm(request.POST, request.FILES)
        if f.is_valid():
            product = f.save(commit=False)
            if not f.cleaned_data['image']:
                product.image = "white.png"
            product.save()
            return redirect('drinks')
    else:
        f = DrinkForm()
    return render(request, 'drinks/drinkAdmin/drink_add.html', context={'f': f})


def drink_edit(request, drink_id):
    product = Product.objects.get(pk=drink_id)
    if request.method == 'POST':
        f = DrinkForm(request.POST, instance=product)
        if f.is_valid():
            f.save()
            return redirect('drinks')
    else:
        f = DrinkForm(instance=product)

    return render(request, 'drinks/drinkAdmin/drink_edit.html', {'f': f, 'product': product})


def drink_toggle(request, drink_id):
    product = Product.objects.get(pk=drink_id)
    product.active = not product.active
    product.save()
    return redirect('drinks')


def drink_change_price(request, drink_id):
    product = Product.objects.get(pk=drink_id)
    if request.method == 'POST':
        form = ChangePriceForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('drinks')
    else:
        form = ChangePriceForm(instance=product)

    return render(request, 'drinks/drinkAdmin/drink_change_price.html', {'f': form, 'product': product})


def drink_restock(request, drink_id):
    product = Product.objects.get(pk=drink_id)
    if request.method == 'POST':
        f = RestockForm(request.POST)
        if f.is_valid():
            restock = InventoryCheck()
            restock.product = product
            restock.check_type = restock.CheckChoices.RESTOCK
            restock.correction_value = f.cleaned_data['bottles']
            restock.save()

            product.stock += f.cleaned_data['bottles']
            product.save()
            return redirect('drinks')
    else:
        f = RestockForm()
    return render(request, 'drinks/drinkAdmin/restock.html', context={'f': f, 'product': product})


def drink_count(request, drink_id):
    product = Product.objects.get(pk=drink_id)
    if request.method == 'POST':
        f = RestockForm(request.POST)
        if f.is_valid():
            restock = InventoryCheck()
            restock.product = product
            restock.check_type = restock.CheckChoices.COUNTING
            restock.correction_value = f.cleaned_data['bottles'] - product.stock
            restock.save()

            product.stock = f.cleaned_data['bottles']
            product.save()
            return redirect('drinks')
    else:
        f = RestockForm()
    return render(request, 'drinks/drinkAdmin/drink_count.html', context={'f': f, 'product': product})


def drinks(request):
    products = Product.objects.all().order_by('-active', 'name')  # - means reverse
    return render(request, 'drinks/drinkAdmin/drink_dashboard.html', context={'products': products})


def drink_recalculate_stock(request):
    for product in Product.objects.all():
        product.validate_stock()
    return redirect('drinks')

drinks/views/prices.py
from django.shortcuts import render, redirect

from drinks.forms import PriceForm
from drinks.models import Price


def add(request):
    if request.method == 'POST':
        f = PriceForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('prices_dashboard')
    else:
        f = PriceForm()

    return render(request, 'drinks/priceAdmin/price_add.html', context={'f': f})


def edit(request, price_id):
    price = Price.objects.get(pk=price_id)
    if request.method == 'POST':
        f = PriceForm(request.POST, instance=price)
        if f.is_valid():
            f.save()
            return redirect('prices_dashboard')
    else:
        f = PriceForm(instance=price)

    return render(request, 'drinks/priceAdmin/price_edit.html', context={'f': f, 'price': price})


def delete(request, price_id):
    price = Price.objects.get(pk=price_id)
    price.delete()
    return redirect('prices_dashboard')


def prices_dashboard(request):
    prices_obj = Price.objects.all()
    return render(request, 'drinks/priceAdmin/price_dashboard.html', context={'prices': prices_obj})

drinks/views/user.py
from django.db import models
from django.shortcuts import redirect, render

from drinks.forms import UserEditForm, DebtForm, TransactionForm
from drinks.models import Profile


def user_add(request):
    if request.method == 'POST':
        f = UserEditForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('user_dashboard')
    else:
        f = UserEditForm()
    return render(request, 'drinks/userAdmin/user_add.html', context={'f': f})


def user_edit(request, user_id):
    user = Profile.objects.get(pk=user_id)
    if param := request.GET.get('delete'):
        if param == "true":
            user.delete()
            return redirect('user_dashboard')
    if request.method == 'POST':
        f = UserEditForm(request.POST, instance=user)
        if f.is_valid():
            f.save()
            return redirect('user_dashboard')
    f = UserEditForm(instance=user)

    return render(request, 'drinks/userAdmin/user_edit.html', context={'f': f, 'profile': user})


def user_dashboard(request):
    if request.GET.get('sort'):
        profiles = Profile.objects.exclude(username__exact="").order_by('room_number', 'username')
    else:
        profiles = Profile.objects.exclude(username__exact="").order_by('username')

    flatmates = [p for p in profiles if p.sorting_order == Profile.ProfileType.FLATMATE]
    guests = [p for p in profiles if p.sorting_order == Profile.ProfileType.GUEST]
    total_balances = Profile.objects.filter(active=True).aggregate(models.Sum("balance"))
    positive_balances = Profile.objects.filter(active=True, balance__gte=0).aggregate(models.Sum("balance"))
    negative_balances = Profile.objects.filter(active=True, balance__lt=0).aggregate(models.Sum("balance"))

    pos_user = Profile.objects.all().order_by("-balance").first()
    neg_user = Profile.objects.all().order_by("balance").first()

    context = {'flatmates': flatmates, 'guests': guests,
               'total_balances': list(total_balances.values())[0],
               'positive_balances': list(positive_balances.values())[0],
               'negative_balances': list(negative_balances.values())[0],
               'pos_user': pos_user,
               'neg_user': neg_user
               }
    return render(request, 'drinks/userAdmin/user_dashboard.html', context=context)


def pay(request):
    if request.method == 'GET':
        if request.GET.get("target"):
            target = Profile.objects.get(pk=request.GET.get("target"))
            f = DebtForm(initial={'target': target}, hide_source=True)
            return render(request, 'drinks/userAdmin/user_paydebt.html', context={'f': f, 'profile': target})
        else:
            f = DebtForm()
            f.fields['target'].queryset = Profile.objects.exclude(active=False).order_by("sorting_order", 'username')
            return render(request, 'drinks/userAdmin/user_paydebt.html', context={'f': f})

    if request.method == 'POST':
        f = DebtForm(False, request.POST)
        if f.is_valid():
            f.save()
            return redirect('dashboard')

        return render(request, 'drinks/userAdmin/user_paydebt.html', context={'f': f})


def transfer(request):
    if request.GET.get("source"):
        source = Profile.objects.get(pk=request.GET.get("source"))
        f = TransactionForm(initial={'source': source})
        f.fields['target'].queryset = Profile.objects.exclude(active=False).order_by("sorting_order", 'username')
    else:
        f = TransactionForm()

    if request.method == 'POST':
        f = TransactionForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('dashboard')

    return render(request, 'drinks/userAdmin/user_transaction.html', context={'f': f})

drinks/views/views.py
from django.shortcuts import render, redirect

from drinks.models import Profile, Product, Sale


# Create your views here.

def dashboard(request):
    sorting_method = request.GET.get('sort', None)
    profiles = Profile.objects.exclude(username__exact="").filter(active=True)
    if sorting_method == "room":
        profiles = profiles.order_by("room_number")
    else:
        profiles = profiles.order_by("username")

    flatmates = [p for p in profiles if p.sorting_order == Profile.ProfileType.FLATMATE]
    guests = [p for p in profiles if p.sorting_order == Profile.ProfileType.GUEST]
    return render(request, 'drinks/dashboard.html',
                  context={'flatmates': flatmates, 'guests': guests})


def history(request):
    sales = Sale.objects.all().order_by('-time')[:15]  # get 15 latest sales
    return render(request, 'drinks/history.html', context={'sales': sales})


def undo_sale(request, sale_id):
    sale = Sale.objects.get(pk=sale_id)
    sale.product.stock += sale.amount
    sale.product.save()
    sale.delete()
    return redirect('history')


def order_user(request, user_id):
    try:
        user = Profile.objects.get(pk=user_id)
    except Profile.DoesNotExist:
        return redirect('dashboard')
    products = Product.objects.filter(active=True).order_by('dashboard_order', 'name')
    return render(request, 'drinks/ordering.html', context={"user": user, "products": products})


def order_drink(request, user_id, product_id):
    product = Product.objects.get(pk=product_id)
    profile = Profile.objects.get(pk=user_id)

    sale = Sale()
    sale.amount = 1
    sale.product = product
    sale.profile = profile
    sale.price = sale.product.current_price.amount * sale.amount
    sale.save()

    product.stock -= sale.amount
    product.save()
    # no need to change the profile balance since this is done in the save functions of the Sale class

    return render(request, 'drinks/sale_ok.html', context={'user_id': user_id, })

drinks/templates/drinks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Drinks</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    {% block head %}
    {% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static 'drinks/dashboard.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item align-middle">
            <a class="nav-item btn btn-light " href="{% url 'dashboard' %}">
                <img src="{% static 'house.png' %}" width="20" height="20" alt="home"> Dashboard
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-links " href="{% url 'history' %}">History</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-links" href="{% url 'user_dashboard' %}">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-links" href="{% url 'drinks' %}">Drinks</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-links" href="{% url 'prices_dashboard' %}">Prices</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link navbar-links dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
               data-toggle="dropdown">
                Statistics
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'statistics:stock' %}">Stock</a>
                <a class="dropdown-item" href="{% url 'statistics:drinks_of_user' %}">Drinks of user</a>
                <a class="dropdown-item" href="{% url 'statistics:users_of_drink' %}">Users of drink</a>

            </div>
        </li>
    </ul>
</nav>
{% block main_content %}
{% endblock %}
<script type="application/javascript" src="{% static 'jquery.slim.min.js' %}"></script>
<script type="application/javascript" src="{% static 'bootstrap.bundle.min.js' %}"></script>

</body>
</html>

drinks/templates/drinks/dashboard.html
{% extends 'drinks/base.html' %}
{% load drinks %}

{% block main_content %}
    <div class="container-fluid p-3">
        <div class="row mb-3">
            <div class="col">
                <h3>Click your name to order a drink:</h3>
            </div>
            <div class="col text-right mr-3">
                <div class="btn-group">
                    <a class="btn btn-secondary" href="{% url 'dashboard' %}">A-Z &#8595;</a>
                    <a class="btn btn-secondary" href="{% url 'dashboard' %}?sort=room">Room # &#8595;</a>
                </div>
            </div>
        </div>
        {% include 'drinks/includes/user_ov.html' with url="order_user" %}
    </div>
{% endblock %}

drinks/templates/drinks/error.html
{% extends 'drinks/base.html' %}

{% block main_content %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col">
                <h1 class="text-warning">Error</h1>
                <h3>{{ message }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a class="btn btn-outline-primary" href="{% url 'dashboard' %}">Back to main menu</a>
            </div>
        </div>
    </div>
{% endblock %}

drinks/templates/drinks/history.html
{% extends 'drinks/base.html' %}
{% block head %}
    <script type="application/javascript">
        function confirm_delete(url) {
            var r = confirm("Do you really want to delete this sale? This can't be undone");
            if (r === true) {
                window.location.href = url;
            }
        }
    </script>
{% endblock %}

{% block main_content %}
    <div class="container-fluid p-3">user
        <div class="row">
            <div class="col">
                <h4>Overview over the last 15 sales</h4>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <th>Time</th>
                        <th>Buyer</th>
                        <th>Product</th>
                        <th>delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for sale in sales %}
                        <tr>
                            {# https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#std:templatefilter-date #}
                            <td>{{ sale.time|date:'d.m.y G:i' }}</td>
                            <td>{{ sale.profile.username }}</td>
                            <td>{{ sale.product.name }}</td>
                            <td><a class="btn btn-sm btn-danger"
                                   onclick="confirm_delete('{% url 'undo_sale' sale.pk %}');">delete</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

drinks/templates/drinks/ordering.html
{% extends 'drinks/base.html' %}
{% load drinks %}

{% block head %}
    <meta http-equiv="refresh" content="10; url={% url 'dashboard' %}"/>
{% endblock %}

{% block main_content %}
    <div class="container-fluid p-3">
        <div class="row">
            <div class="col">
                <h3>Hello {{ user.username }}, choose your drink:</h3>
            </div>
            <div class="col text-right">
                <a class="btn btn-outline-secondary" href="{% url 'dashboard' %}">go back</a>
            </div>
        </div>
        {% if not products %}
            <div class="row mt-2">
                <div class="col">
                    <h5>There are no drinks configured. Please add some:</h5>
                    <a class="btn-outline-success btn" href="{% url 'drinks' %}">drinks configuration</a>
                </div>
            </div>

        {% endif %}

        {% include 'drinks/includes/drinks_ov.html' %}
        <hr>
        <div class="row mt-4">
            <div class="col">
                <h5>Account balance: </h5>
                {% if user.balance > 0 %}
                    <h4 class="text-success">{{ user.balance|floatformat:2 }} €</h4>
                {% else %}
                    <h4 class="text-danger">{{ user.balance|floatformat:2 }} €</h4>
                {% endif %}
                <a class="btn btn-primary my-1" href="{% url 'user_pay' %}?target={{ user.pk }}">Top up <u>your</u>
                    balance</a>

                <a class="btn btn-primary my-1" href="{% url 'user_transfer' %}?source={{ user.pk }}">Transfer money to
                    <u>other</u> users</a>
            </div>
            <div class="col-9">
                <p>Sales in last 30 days: {{ user.d30_money_spent|floatformat:2 }} € with {{ user.d30_amount_of_sales }}
                    Sales</p>
                <p>Sales total: {{ user.total_money_spent|floatformat:2 }} € with {{ user.total_amount_of_sales }}
                    Sales</p>
            </div>
        </div>

    </div>
{% endblock %}

drinks/templates/drinks/sale_ok.html
{% extends 'drinks/base.html' %}

{% block head %}
    <meta http-equiv="refresh" content="0.5; url={% url 'order_user' user_id %}"/>
{% endblock %}

{% block main_content %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col">
                <h1>Thanks :)</h1>
            </div>
        </div>
    </div>
{% endblock %}