drinkManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drinks.urls')),
    path('statistics/', include('stats.urls'))
]

stats/urls.py
from django.urls import path

from .views import views, data

app_name = "statistics"

urlpatterns = [
    path('drinks', views.stock, name="stock"),
    path('drinksofuser', views.drinks_of_user, name="drinks_of_user"),
    path('usersofdrink', views.users_of_drink, name="users_of_drink"),

    # data
    path('data/stock', data.stock, name="api_stock"),
    path('data/loss', data.loss, name="api_loss"),
]

stats/models.py
# Create your models here.

stats/views/data.py
from django.shortcuts import render
from django.views.decorators.clickjacking import xframe_options_exempt

from stats.statistics import get_stock, get_loss


@xframe_options_exempt
def stock(request):
    return render(request, 'stats/stat_iframe.html', {'code': get_stock()})


@xframe_options_exempt
def loss(request):
    return render(request, 'stats/stat_iframe.html', {'code': get_loss()})

stats/views/views.py
from django.shortcuts import render

from drinks.models import Profile, Product


def stock(request):
    return render(request, 'stats/stock.html')


def drinks_of_user(request):
    users = Profile.objects.filter(active=True).order_by('username')
    return render(request, 'stats/drinks_of_user.html', {'users': users})


def users_of_drink(request):
    products = Product.objects.filter(active=True).order_by('dashboard_order', 'name')
    return render(request, 'stats/users_of_drink.html', {'products': products})

stats/templates/stats/base.html
{% extends 'drinks/base.html' %}
{% load static %}


{% block head %}
    <script type="application/javascript" src="{% static 'plotly-2.6.3.min.js' %}"></script>
    {% block stats_head %}
    {% endblock %}
{% endblock %}

{% block main_content %}
    <h1> Hello from new template</h1>
{% endblock %}

stats/templates/stats/drinks_of_user.html
{% extends 'stats/base.html' %}
{% load user_statistics %}

{% block main_content %}
    <div class="container-fluid p-3">
        <div class="row">
            <div class="col">
                <h5>Shows the most bought drinks of each person in the last 30 days</h5>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card-columns" style="column-count: 5;">
                    {% for user in users %}
                        {% drinks_of_user user %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

stats/templates/stats/stat_iframe.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'plotly-2.6.3.min.js' %}"></script>
</head>
<body>
{{ code|safe }}
</body>
</html>

stats/templates/stats/stock.html
{% extends 'stats/base.html' %}
{% load static %}

{% block main_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col" id="stock-chart">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="{% url 'statistics:api_stock' %}">Fetching data</iframe>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="embed-responsive embed-responsive-16by9 ">
                    <iframe class="embed-responsive-item" src="{% url 'statistics:api_loss' %}"></iframe>
                </div>
                <small>negative numbers mean loss in drinks</small>
            </div>
        </div>
    </div>
{% endblock %}

stats/templates/stats/users_of_drink.html
{% extends 'stats/base.html' %}
{% load user_statistics %}

{% block main_content %}
    <div class="container-fluid p-3">
        <div class="row">
            <div class="col">
                <h5>Shows who bought each drink in the last 30 days</h5>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card-columns" style="column-count: 5;">
                    {% for product in products %}
                        {% users_of_drink product %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}